### ISSUE TITLE
No Support for other formats of create field

### ISSUE THREAD

**Issue by CyberTaoFlow** [MarkBaggett/domain_stats#12]
I have found some providers use a different format for the creation data.
For example:

whois linux.org.tr | grep -i creat
Created on..............: 2000-Jun-28.

Or another widely seen example being the EDUCAUSE whois server:

whois berkeley.edu | grep '[a-Z]-[0-9][0-9][0-9][0-9]'

Domain record activated:    24-Apr-1985
Domain record last updated: 26-Sep-2018
Domain expires:             31-Jul-2019

For the latter case its not that big of a deal for my use case which I workaround by not sending queries for edu TLD but some users may want that.

I have also found some TLD's that are known to  either not provide whois or provide limited records, one such is .to (tonga).  Again I handle that by not sending those to the server however it appears the data is available by performing a GET like below:

GET https://www.tonic.to/whois?talk.to
<pre>
Domain:               talk.to
Created on:           Tue Apr 12 01:27:36 2011
Last edited on:       Wed Jun 07 21:57:52 2017
Expires on:           Mon Apr 12 01:27:36 2021
Primary host add:     205.251.199.138
Primary host name:    ns-1930.awsdns-49.co.uk
Secondary host add:   205.251.192.119
Secondary host name:  ns-119.awsdns-14.com

**Comment by MarkBaggett** [comment]
Thanks for reporting this.   I actually don't do the whois queries directly.   domain stats provided the API, Caching and integration of other data such as Alexa top 1 million.   I use a module called python-whois do to the heavy lifting so that I don't have to worry about this.  If you will open an issue with them I'll grab a copy of their code and see if I can offer them a pull request with a simple fix      

https://bitbucket.org/richardpenman/pywhois
